---
# Task 13: Utility Scripts for UM5606

- name: Create user bin directory
  file:
    path: "/home/{{ target_user }}/.local/bin"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0755'

# Copy all utility scripts from files
- name: Copy utility scripts
  copy:
    src: "scripts/{{ item }}"
    dest: "/home/{{ target_user }}/.local/bin/{{ item }}"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0755'
  loop:
    - power-mode
    - power-mode-menu
    - display-toggle
    - dock-handler
    - sysinfo
    - update-all
    - wifi-switch
    - vpn-control
    - backup-system
    - search-packages
    - wallpaper-rotate
    - oled-protect
    - audio-switch
    - vol
    - btrfs-maintenance
    - btrfs-snapshot
    - btrfs-info
    - find-package